### ISSUE TITLE
Visual Studio 2019编译不通过

### ISSUE THREAD

**Issue by yuxiaoyuan0406** [matrixcascade/PainterEngine#1]
错误信息如下
```
1>${WorkPath}\PainterEngine_test_1\PainterEngine\PainterEngineHelper.c(254,1): error C4996:  'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>正在生成代码...
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\stdio.h(208): message :  参见“fopen”的声明
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\stdio.h(208): message : ${WorkPath}\PainterEngine_test_1\PainterEngine\Kernel\PX_Sync.c(944) : error C4703: 使用了可能未初始化的本地指针变量“pClient”
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\stdio.h(208): message : ${WorkPath}\PainterEngine_test_1\PainterEngine\Kernel\PX_Script_Interpreter.c(6055) : error C4703: 使用了可能未初始化的本地指针变量“pfunc”
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\stdio.h(208): message : ${WorkPath}\PainterEngine_test_1\PainterEngine\Kernel\PX_Script_Interpreter.c(6419) : error C4703: 使用了可能未初始化的本地指针变量“plastop”
1>已完成生成项目“PainterEngine_test_1.vcxproj”的操作 - 失败。
```

另外是否考虑一下增加cpp兼容性？增加跨平台兼容性
```
#ifdefined __cplusplus
extern "C" {
#endif

/*
code here
*/

#ifdefined __cplusplus
}
#endif
```

**Comment by yuxiaoyuan0406** [comment]
附上代码
```cpp
#include "PainterEngine/PainterEngineHelper.h"

int main() {
	PX_Initialize((char*)"First PainterEngine Project", 800, 600);
	while (PX_Loop()) {
		;
	}
}
```

**Comment by matrixcascade** [comment]
VS2019 禁用了fopen 标准库函数,该函数在PainterEngineHelper中引用,请在 项目->属性->C/C++->预处理器->预处理器定义中添加_CRT_SECURE_NO_WARNINGS或者修改该函数为fopen_s

PainterEngine/PainterEngineHelper.h 已更新该宏

PainterEngine 核心部分为纯C语言开发.cpp引用代码可以自行增加该宏

**Comment by ziyht** [comment]
1>c:\users\ziyht\desktop\workspace\painterengine\space old driver\space old driver\sod_runtime.h(7): fatal error C1083: 无法打开包括文件: “../../../PainterEngine/platform/windows/Platform_Windows_D2D.h”: No such file or directory
1>  SOD_Game.c
1>c:\users\ziyht\desktop\workspace\painterengine\space old driver\space old driver\sod_runtime.h(7): fatal error C1083: 无法打开包括文件: “../../../PainterEngine/platform/windows/Platform_Windows_D2D.h”: No such file or directory
1>  MatrixEffect_ui.c
1>c1 : fatal error C1083: 无法打开源文件: “..\..\PainterEngine\Effect\MatrixEffect_ui.c”: No such file or directory
1>  正在生成代码...
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

编译 space old dirver 报的错，查看了一下，确实没有相关文件，.h 和 .c 均没有

**Comment by neko-para** [comment]
没有安装Direct2D
可以考虑vcpkg

**Comment by matrixcascade** [comment]
该错误是因为没有配置正确的路径导致的,可以依据情况修改对应include到正确的位置,这些代码在painterengine里都可以找到

**Comment by matrixcascade** [comment]
目前新版本已修正该问题
