### ISSUE TITLE
A bug appear when compile on the linux 

### ISSUE THREAD

**Issue by fangyuanbuyi** [matrixcascade/PainterEngine#112]
报错信息如下:
```
/usr/bin/ld: ../../runtime/PainterEngine_Application.o: in function `PainterEngine_InitializeAudio':
PainterEngine_Application.c:(.text+0x88b): undefined reference to `PX_AudioInitialize'
collect2: error: ld returned 1 exit status
```

分析:
这是由于 linux 相关包中没有 px_audio 的实现,而在 `runtime/PainterEngine_Application.h` 中,声明了 `platform/modules/px_audio.h` 头文件  
而 `platform/modules/px_audio.h` 有这么一段宏声明 
```
#ifndef PX_AUDIO_H
#define PX_AUDIO_H
```
这段宏声明以及头文件的依赖关系会导致 `runtime/PainterEngine_Application.c` 的 PainterEngine_InitializeAudio 函数 在判断是否存在 `PX_AUDIO_H` 这宏常量时始终为真,从而引发错误  

个人解决方案:
- 修改 `platform/linux/make` 文件,在编译 runtime 的 c文件时传入宏PX_LINUX_NO_AUDIO_H
- 修改 `rumtime/PainterEngine_Application.h`文件, 仅当 PX_LINUX_NO_AUDIO_H 不存在时才导入 `platform/modules/px_audio.h`

修改 `platform/linux/make` :

before updated
```
$(painterengine_path)/runtime/%.o:$(painterengine_path)/runtime/%.c 
	gcc -c $^ -o $@ -I "$(painterengine_path)"
```
after updated
```
$(painterengine_path)/runtime/%.o:$(painterengine_path)/runtime/%.c 
	gcc -DPX_LINUX_NO_AUDIO_H -c $^ -o $@ -I "$(painterengine_path)"
```

修改 `rumtime/PainterEngine_Application.h`:

before updated
```
#include "platform/modules/px_audio.h"
```
after updated
```
#ifndef PX_LINUX_NO_AUDIO_H
#include "platform/modules/px_audio.h"
#endif
```

**Comment by matrixcascade** [comment]
将在下次更新时修正

**Comment by matrixcascade** [comment]
这个问题已经在更新修正
