### ISSUE TITLE
想问下有文档吗？

### ISSUE THREAD

**Issue by udbhssnhwgf** [matrixcascade/PainterEngine#115]
我其实看了小部分的内容，内存申请，字符分割，json 解析啥的。然后想看编译器的部分。但代码很多，没有注释，没有调用例子，实在有点不知道从哪下手。

**Comment by udbhssnhwgf** [comment]
我其实看了小部分的内容，内存申请，字符分割，json 解析啥的。然后想看编译器的部分。但代码很多，没有注释，没有调用例子，实在有点不知道从哪下手。

**Comment by matrixcascade** [comment]
正在制作中

**Comment by matrixcascade** [comment]
https://github.com/matrixcascade/PainterEngine/blob/master/documents/PainterEngine%20the%20book.md 文档已公布
