### ISSUE TITLE
PX_LoadFontModuleFromFile ERROR

### ISSUE THREAD

**Issue by Chaotze** [matrixcascade/PainterEngine#12]
I'm a starter and cloned your repo today (3rd May, 2020).
While I tried to use the font module like your answer on [https://www.zhihu.com/question/35391145](url) on VS2019, it said `Error C3861: 'PX_LoadFontModuleFromFile': identifier not found.` Then I searched all the PainterEngine codes, I could not find the function either.
So, have you moved these codes, or you created a new way to do this work? How should I do to render fonts by custom?
BTW, your jpg/png decoder libs seems to be 32-bit. If I want a 64-bit version, what should I do?

**Comment by matrixcascade** [comment]
1.This bug has been fixed in the current version
2.rebuild libpng(http://www.libpng.org/pub/png/libpng.html) & libjepg(http://libjpeg.sourceforge.net/)  ,Replace the old libraries
