### ISSUE TITLE
请问这个项目能用来搭建网站吗？

### ISSUE THREAD

**Issue by zoucap** [matrixcascade/PainterEngine#129]
比如做做个人博客啥的。
如果可以的话，大概要怎么搞呢？

**Comment by matrixcascade** [comment]
可以用来搭建网站,PainterEngine官网首页就是由PainterEngine编写的
可以但不建议用于编写博客,因为其它适合编写网页前后端的语言更适合做这个工作,且有很多成熟的框架.PainterEngine更适合做一些网页特效或需要性能加速的运算工作
如果你坚持要这么做,其实就和C语言写个文章浏览器差不多,当然也通过websocket实现动态更新.
