### ISSUE TITLE
在Dev-C++ 中 存在一个编译问题

### ISSUE THREAD

**Issue by cyder-zz** [matrixcascade/PainterEngine#2]
30	35	C:\Dev C++\PainterEngineTest\PainterEngine\Core\PX_Packet.c	[Error] invalid conversion from 'const void*' to 'px_void* {aka void*}' [-fpermissive]

PX_Packet.c   第30行 35列
<img width="931" alt="批注 2019-07-14 095158" src="https://user-images.githubusercontent.com/11573556/61178413-18190280-a61f-11e9-9735-a85762b36734.png">

**Comment by cyder-zz** [comment]
另外，从网站上下载源代码zip文件，解压缩提示有问题。
<img width="421" alt="批注 2019-07-14 101353" src="https://user-images.githubusercontent.com/11573556/61178495-5236d400-a620-11e9-8e0f-50706cb22eb2.png">

**Comment by cyder-zz** [comment]
<img width="948" alt="批注 2019-07-14 102315" src="https://user-images.githubusercontent.com/11573556/61178542-8363d400-a621-11e9-902b-fa4d896a3e15.png">

**Comment by cyder-zz** [comment]
使用的是C++  编译模式

**Comment by cyder-zz** [comment]
https://blog.csdn.net/searchwang/article/details/30036129
参照上文，修改
<img width="373" alt="批注 2019-07-14 110813" src="https://user-images.githubusercontent.com/11573556/61178796-ca54c800-a627-11e9-93cf-cded7963117c.png">
 通过。

**Comment by cyder-zz** [comment]
产生新问题

<img width="911" alt="批注 2019-07-14 111043" src="https://user-images.githubusercontent.com/11573556/61178803-27e91480-a628-11e9-84a4-fd8e76998ee5.png">

**Comment by cyder-zz** [comment]
把编译选项由64位，变成32位，通过，又遇到前面类似的问题。
<img width="872" alt="批注 2019-07-14 164038" src="https://user-images.githubusercontent.com/11573556/61181272-731a1c00-a656-11e9-8ed4-cb61633abc06.png">

**Comment by cyder-zz** [comment]
https://bytes.com/topic/c/answers/490531-invalid-conversion-const-void-void

参照上文，使用  const_cast<char*>() 转换， OK。
  So an explicit cast is needed.
IMO the easiest in such a context is to use a C-style cast:
Start((void*)"hi");
With a C++ cast, you'd write:
Start( const_cast<char*>("hi") );


<img width="958" alt="批注 2019-07-14 165636" src="https://user-images.githubusercontent.com/11573556/61181434-21bf5c00-a659-11e9-8e57-5ab949daec1f.png">

**Comment by cyder-zz** [comment]
碰到新问题

<img width="949" alt="批注 2019-07-14 171003" src="https://user-images.githubusercontent.com/11573556/61181507-508a0200-a65a-11e9-8969-28e7cfb216e1.png">

**Comment by matrixcascade** [comment]
正在修正

**Comment by matrixcascade** [comment]
已修正
