### ISSUE TITLE
Windows下makefile编译段错误

### ISSUE THREAD

**Issue by ewoifuoi** [matrixcascade/PainterEngine#28]
![QQ截图20210403174535](https://user-images.githubusercontent.com/47176322/113474749-75647f80-94a4-11eb-9375-a6601b8ba93e.png)

**Comment by yuanchilin** [comment]
![image](https://user-images.githubusercontent.com/49054989/114679911-32759800-9d3f-11eb-8835-4a68a89280eb.png)

**Comment by yuanchilin** [comment]
我也遇见了一点小小的困难，
