### ISSUE TITLE
SLES/OpenSLES.h: No such file or directory

### ISSUE THREAD

**Issue by Loikeid** [matrixcascade/PainterEngine#32]
## SLES/OpenSLES.h: No such file or directory

When I `cd` into `PainterEngine/platform/linux`, and use `sudo make` command to install the engine, the error occured. I wander if I have to install Android NDK or anything else?

By the way, my platform via `uname -a` is `Linux VM-4-14-ubuntu 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`.

**Comment by matrixcascade** [comment]
1.Make sure freeglut has been installed
  sudo apt-get install build-essential freeglut3 freeglut3-dev binutils-gold
2.remove PainterEngine/platform/linux/px_audio.c(the file has been removed in latest version)
3.retry
