### ISSUE TITLE
api文档错误

### ISSUE THREAD

**Issue by synodriver** [matrixcascade/PainterEngine#35]
```px_void* PX_ListPush(px_list *list, px_void *data, px_int size)``` 和api文档的不一致

```px_byte *PX_MemoryFine(px_memory *memory, const px_void *buffer, px_int size)``` api文档里面是find

**Comment by synodriver** [comment]
~~另外那个[cmake的pr](https://github.com/matrixcascade/PainterEngine/pull/30)什么时候merge啊~~

**Comment by matrixcascade** [comment]
第一个是文档错了,第二个是代码单词拼错了,已更正
