### ISSUE TITLE
Dev C++ 编译 ，还存在一个 类型转换错误

### ISSUE THREAD

**Issue by cyder-zz** [matrixcascade/PainterEngine#5]
函数指针转换错误还没修正。如下图：
<img width="946" alt="批注 2019-07-17 222525" src="https://user-images.githubusercontent.com/11573556/61383927-2cd8ed00-a8e2-11e9-9e5a-e5ae3d45748d.png">

**Comment by cyder-zz** [comment]
2988	21	C:\Dev C++\PainterEngineTest\PainterEngine\Kernel\PX_Script_VM.c	[Error] invalid conversion from 'PX_ScriptVM_Function_Modules {aka int (*)(PX_ScriptVM_Instance*)}' to 'const px_void* {aka const void*}' [-fpermissive]

**Comment by matrixcascade** [comment]
已修正该问题
