### ISSUE TITLE
此项目底层依赖OpenGL？

### ISSUE THREAD

**Issue by weiyinfu** [matrixcascade/PainterEngine#58]
https://www.painterengine.com/
官网上显示，
> PainterEngine由C89标准及部分拓展编写,不依赖任何C标准库及三方库。
<img width="757" alt="image" src="https://user-images.githubusercontent.com/16095925/170883795-667f978d-6257-4b72-9c07-00e9172e4be4.png">

而实际上用到了OpenGL？
<img width="882" alt="image" src="https://user-images.githubusercontent.com/16095925/170883807-674eca49-8be6-46c6-9f0c-4e7b146abd7e.png">

**Comment by matrixcascade** [comment]
不依赖,这里的glut仅仅只是为了将painterengine渲染好的render buffer绘制出来提供一个比较方便的平台接口,即使没有也不造成影响,你可以输出成图片文件或其它任意能显示renderbuffer的接口,并不一定需要使用平台依赖层
