### ISSUE TITLE
基于 PainterEngine Public 的 live 2d 编辑器编译失败

### ISSUE THREAD

**Issue by Jamlee** [matrixcascade/PainterEngine#60]
尝试过 vs2022 和 vs2019, 最后都会报错，看起来是 libpng 和 libjpeg 库有问题：

![image](https://user-images.githubusercontent.com/5196641/189199406-dd2e56fa-0ff5-4229-b673-b4df2ccbf6a2.png)

最终我学着painterEngine的编译版本的样子做了个 mingw +  painterEngine + live 2d ，其中带有 libpng 和 libjpeg ，点击【编译.bat】可编译：
![image](https://user-images.githubusercontent.com/5196641/189199745-0e2615b1-5b4a-4a58-8e03-bd8af55d6923.png)

分享给拐子快速入坑，mingw +  painterEngine + live 2d（370MB）：链接：https://pan.baidu.com/s/1uVD7mhzpMjc0A_YIT_PjGw?pwd=msib 
提取码：msib 
--来自百度网盘超级会员V3的分享

**Comment by matrixcascade** [comment]
已收到反馈，目前painterengine已自带原生png encoder，decoder，我会近期更新编辑器不再依赖libpng

**Comment by matrixcascade** [comment]
已修正
