### ISSUE TITLE
或许是个bug

### ISSUE THREAD

**Issue by wuke32767** [matrixcascade/PainterEngine#62]
在\kernel\PX_Object_CursorButton.c的函数PX_Object_CursorButtonCreate(px_memorypool *mp,..)中，visual studio发现：
```
	pObject=PX_ObjectCreate(mp,Parent,(px_float)x,(px_float)y,0,(px_float)Width,(px_float)Height,0);
	if (pObject==PX_NULL)
	{
		MP_Free(pObject->mp,pCb);
		return PX_NULL;
	}
```
这一部分中`MP_Free`的第一个参数`pObject->mp`，`pObject`是一个`nullptr`，不能解引用。
联系上文：
```
	PX_Object_CursorButton *pCb=(PX_Object_CursorButton *)MP_Malloc(mp,sizeof(PX_Object_CursorButton));
```
也许你的意思是`MP_Free(mp,pCb);`?

**Comment by matrixcascade** [comment]
是的,您的解释没错这里确实是个bug,这里应该为MP_Free(mp,pCb),马上修正
