### ISSUE TITLE
PainterEngine\Core\PX_Typedef.c:1404 error: conflicting types for 'PX_strset'

### ISSUE THREAD

**Issue by bushix** [matrixcascade/PainterEngine#7]
在PX_Typedef.c中：
`px_void PX_strset(px_char *dst,const px_char*src)
{
	dst[0]=0;
	PX_strcat(dst,src);
}`
在PX_Typedef.h中：
`px_void PX_strset(px_void *dst,const px_void *src);`

**Comment by matrixcascade** [comment]
感谢指出,已修正
