### ISSUE TITLE
我在docker linux gcc环境下make,make报错

### ISSUE THREAD

**Issue by dc77175363** [matrixcascade/PainterEngine#71]
我在PainterEngine/platform/linux下make,报错
In file included from ../../platform/linux/px_display.c:1:
../../platform/linux/px_display.h:3:10: fatal error: GL/freeglut.h: No such file or directory
    3 | #include <GL/freeglut.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [makefile:48: ../../platform/linux/px_display.o] Error 1
请问如何解决.

**Comment by blueloveTH** [comment]
`sudo apt install freeglut3-dev`
